### ISSUE TITLE
QEMU crash when running sshd in multiarch/ubuntu-core

### ISSUE THREAD

**Issue by QuickJack** [multiarch/ubuntu-debootstrap#10]
The crash happens in armhf-trusty and armhf-xenial. Following is the output of sshd after entering the password as a non-root user (see also #9):

armhf_builder_1 | Server listening on 0.0.0.0 port 22.
armhf_builder_1 | Server listening on :: port 22.
armhf_builder_1 | Accepted password for gitlab_ci_multi_runner from 172.17.0.9 port 38436 ssh2
armhf_builder_1 | **\* stack smashing detected ***: sshd: gitlab_ci_multi_runner terminated
armhf_builder_1 | qemu: uncaught target signal 6 (Aborted) - core dumped
armhf_builder_1 | mm_request_receive: read: Connection reset by peer

**Comment by meyskens** [comment]
What is the host os?

**Comment by QuickJack** [comment]
The host OS that is running the docker engine is Ubuntu 14.04 + Kernel 4.2 (all updates installed). I am using the latest version of docker (1.12.0).

**Comment by moul** [comment]
Hi @QuickJack,

To be 100% sure, can you confirm that your host running Docker is on an `x86_64` processor and that the Docker container you run is in `armhf'?
Sorry for this question, but in the context of multiarch, everything is possible:)

**Comment by QuickJack** [comment]
The host architecture is amd64. The base image is multiarch/ubuntu-core:xenial-armhf. The problem did also occur using multiarch/ubuntu-core:trusty-armhf

**Comment by QuickJack** [comment]
Unfortunately, this bug is still present. However, we also have the "Unsupported syscall: 311" message.

armhf_builder_1        | Server listening on 0.0.0.0 port 22.
armhf_builder_1        | Server listening on :: port 22.
armhf_builder_1        | Accepted password for gitlab_ci_multi_runner from 172.17.0.15 port 51660 ssh2
armhf_builder_1        | qemu: Unsupported syscall: 311
armhf_builder_1        | *** stack smashing detected ***: sshd: gitlab_ci_multi_runner terminated
armhf_builder_1        | qemu: uncaught target signal 6 (Aborted) - core dumped
armhf_builder_1        | mm_request_receive: read: Connection reset by peer
