### ISSUE TITLE
QEMU "unsupported syscall: 384" in multiarch/ubuntu-core:armhf-trusty

### ISSUE THREAD

**Issue by QuickJack** [multiarch/ubuntu-debootstrap#11]

**Comment by QuickJack** [comment]
``` console
root@61d52021f623:/# lsb_release -a
qemu: Unsupported syscall: 384
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Xenial Xerus (development branch)
Release:    16.04
Codename:   xenial
```

**Comment by moul** [comment]
Hi @QuickJack, thank you for reporting,

As qemu needs to implement each new syscalls manually, it sometimes happens that it misses some ones:
- https://bugs.launchpad.net/qemu/+bug/1470170
- https://bugs.launchpad.net/ubuntu/+source/qemu-linaro/+bug/903239
- https://bugs.launchpad.net/qemu/+bug/1042388

In the particular case of lsb_release, I don't think you miss too much information, however, if you need this syscall earlier, do not hesitate to report the error here: https://bugs.launchpad.net/qemu/+bugs

**Comment by QuickJack** [comment]
Thanks @moul for providing the bug reports on launchpad.

**Comment by QuickJack** [comment]
Unfortunately, this bug is still present.

**Comment by MBetters** [comment]
I'm getting the bug as well, present day.
