### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by bebehei** [multiarch/ubuntu-debootstrap#14]
Cool image, but how is this supposed to get built?

I see `update.sh`, but I'm not able to get into its the logic yet and `mkimage.sh` usually needs some parameters. Also executing `update.sh` does nothing on my system. Could someone please update the build-instructions in `README.md`?

Thanks in advance.

**Comment by meyskens** [comment]
The debootstrap image is deprecated it is suggested to use the core one.

**Comment by bebehei** [comment]
Thanks for your answer.
