### ISSUE TITLE
/etc/apt/sources.list is empty

### ISSUE THREAD

**Issue by reinder** [multiarch/ubuntu-debootstrap#17]
My CI system use the multiarch/ubuntu-debootstrap:armhf-xenial image, in the new image the apt sources.list file is empty which wasn't withe the previous image. See issue #1

**Comment by reinder** [comment]
docker image multiarch/ubuntu-debootstrap:armhf-xenial ID=sha256:a18f39fdfab87893787153a11295940fb2f80c6b5fb22edd581d1505db734c78 -> ok

docker image multiarch/ubuntu-debootstrap:armhf-xenial ID=sha256:8c02002a3cc7488cab16027d0e6d53b73219214efb8b7590fe7486220b033f1b -> empty sources.list

**Comment by hurricanehrndz** [comment]
I can confirm the issue, here is the offending commit: https://github.com/multiarch/ubuntu-debootstrap/commit/a96a9c2f819a2da9ad2976121d44475086cc00ac#diff-25e6ad8ebc5d26ba06d2bcb0b220149c
