### ISSUE TITLE
update.sh seems to stop at "mkimage="

### ISSUE THREAD

**Issue by meyskens** [multiarch/ubuntu-debootstrap#4]
Trying to run the update.sh to build some images local it seems to halt at 

```
++ readlink -f mkimage.sh
+ mkimage=
```

not sure if it is me or the file.

**Comment by moul** [comment]
you need to have mkimage.sh pointing (symlink) to https://github.com/docker/docker/blob/master/contrib/mkimage.sh

**Comment by meyskens** [comment]
Thanks!
Now I get `error: debootstrap does not exist or is not executable` while 

```
root@multiarch-build-test:~/ubuntu-debootstrap# debootstrap 
I: usage: [OPTION]... <suite> <target> [<mirror> [<script>]]
I: Try `debootstrap --help' for more information.
E: You must specify a suite and a target.
```

google didn't help :(

**Comment by moul** [comment]
apt-get install debootstrap

**Comment by meyskens** [comment]
did that as said in the comment

**Comment by moul** [comment]
are you building this from a C1 server ? this will only work from an x86_64 box

**Comment by meyskens** [comment]
The C2S, fixed on a fresh install and using the mkimage from /usr/share/docker.io. Now i have a problem after the build that the rootfs can't be rm'ed. Trying to patch the mkimage.sh to umount it first.

**Comment by moul** [comment]
oh ok, I don't have this problem, I run this script as root, maybe it's just a permission issue

**Comment by meyskens** [comment]
I do run it as root too on both the c2 and on travis. Both have the issue

**Comment by meyskens** [comment]
The exact error is `rm: cannot remove ‘/home/travis/build/meyskens/ubuntu-debootstrap/12.04-amd64/rootfs/run/shm’: Device or resource busy` (full log at https://travis-ci.org/meyskens/ubuntu-debootstrap/builds/115023314)

**Comment by meyskens** [comment]
Solved with my patch :) x86_64 works. arm64 seems to have some issue `E: Invalid Release file, no entry for main/binary-arm64/Packages on command`qemu-debootstrap --variant=minbase --components=main --include=wget --arch=arm64 precise /root/ubuntu-debootstrap/12.04-arm64/rootfs`

**Comment by meyskens** [comment]
Caused by #6
