### ISSUE TITLE
Bug in multiarch/ubuntu-debootstrap:armhf-trusty

### ISSUE THREAD

**Issue by QuickJack** [multiarch/ubuntu-debootstrap#9]
/etc/apt/sources.list is empty and thus it is impossible to even install git. Without git we cannot do anything useful. I think git is so fundamental that it should be included by default.

Please fix/ update your docker image.

**Comment by meyskens** [comment]
Try the ubuntu-core one. As i remeber this one is deprecated.

**Comment by QuickJack** [comment]
I tried multiarch/ubuntu-core:armhf-trusty and apt-get is working again.

Thanks a lot!

**Comment by meyskens** [comment]
You're welcome. Should you require more recent builds (eg for non-beta Xenial) I forked it into `meyskens/ubuntu-core` and automated the build of it.

**Comment by QuickJack** [comment]
I am developing a GitLab-CI compatible runner. This allows to build native armhf projects using GitLab. I am using a default runner container (amd64) which connects via ssh to the actual build container (armhf) as user gitlab_ci_multi_runner. Using socialdefect/raspbian-jessie-core as the base works without issues. However, using multiarch/ubuntu-core:armhf-trusty gives the following error log:

armhf_builder_1       | Server listening on 0.0.0.0 port 22.
armhf_builder_1       | Server listening on :: port 22.
armhf_builder_1       | Accepted password for gitlab_ci_multi_runner from 172.17.0.9 port 38436 ssh2
armhf_builder_1       | **\* stack smashing detected ***: sshd: gitlab_ci_multi_runner terminated
armhf_builder_1       | qemu: uncaught target signal 6 (Aborted) - core dumped
armhf_builder_1       | mm_request_receive: read: Connection reset by peer

This is the log output of sshd (started as sshd -D -e).

What I need is a method to implement non-root ssh access to a docker  container based on multiarch/ubuntu-core:armhf-trusty.

**Comment by meyskens** [comment]
Qemu has issues handling some instructions. Make sure you run a recent version(Xenial has many patches). We use gitlab to to native builds on real ARM machines (https://eyskens.me/multiarch-docker-images/)

**Comment by QuickJack** [comment]
I have created a new issue. It is obviously a bug in QEMU. SSH is a requirement for me. I will stick with socialdefect/raspbian-jessie-core until the issue is fixed. Thanks anyway.

I am closing this issue as the original question was answered.
